plugins:
- jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll@6.0.1
title: "SAE TeMV1 2023-2024"
description: "Pagina di supporto al corso Tecniche e Metodologie dei Videogiochi 1. Docente: Andrea Guastadisegni"